services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017
      - REDIS_URI=redis://redis
      - ENABLE_WRITING_HANDLERS=false
    depends_on:
      - mongodb
      - redis
    networks:
      - movies-network
      - mongo-network


  mongodb:
    image: mongo:8.0-rc
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - mongo-network
      - admin-network
      
    
  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - admin-network
    profiles:
      - dev


  redis:
    image: redis:alpine
    networks:
      - movies-network

  
  mongo-seed:
    image: mongo:8.0-rc
    depends_on:
      - mongodb
    command: /mongo-seed.sh
    volumes:
      - ./seeding.json:/seeding.json
      - ./mongo-seed.sh:/mongo-seed.sh
    profiles:
      - dev
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017
    networks:
      - mongo-network


network:
  movies-network: # Movies API and Redis
    driver: bridge
  db-network: # Movies API and MongoDB and mongo-seed
    driver: bridge
  admin-network:  # Mongo Express and MongoDB
    driver: bridge

volumes:
  mongodb-data:
    driver: local